version: "3.9"
services:
  zuul-app:
    image: zuul-app
    build: 
      context: ./spring-cloud-starter-netflix-zuul
      dockerfile: Dockerfile
    # volumes:
    #   - ./spring-cloud-starter-netflix-zuul:/opt:rw
    ports:
      - "8080:8080"

  webflux-app:
    image: webflux-app
    build: 
      context: ./spring-cloud-starter-gateway-webflux
      dockerfile: Dockerfile
    # volumes:
    #   - ./spring-cloud-starter-gateway-webflux:/opt:rw
    ports:
      - "8081:8081"
 
  mvc-app:
    image: mvc-app
    build: 
      context: ./spring-cloud-starter-gateway-mvc
      dockerfile: Dockerfile
    # volumes:
    #  - ./spring-cloud-starter-gateway-mvc:/opt:rw
    ports:
      - "8082:8082"
 
  grafana:
    container_name: container-grafana
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini

 

# Start the application stack defined in docker-compose.yml
# docker-compose up -d

# Stop the application stack
# docker-compose down