version: "3.9"
services:
  grafana:
    container_name: container-grafana
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini

# Start the application stack defined in docker-compose.yml
# docker-compose up -d

# Stop the application stack
# docker-compose down